version: 2

jobs:
  build:
    docker:
      - image: busybox
    steps:
      - run: echo "this is build task"  
  react:
    docker:
      - image: circleci/node:9.11
    steps:
      - run: PATH=$PATH:/home/circleci/.local/bin; export PATH && sudo apt-get -y -qq update && sudo apt-get -y -qq install python3 python3-dev && sudo curl -O https://bootstrap.pypa.io/pip/3.4/get-pip.py && python3 get-pip.py --user && pip install awscli --upgrade --user
      - checkout
      - run: yarn build
      - run : cd docker-codes/http-server/guteam/
      - run: aws s3 sync ./build s3://guteam-production --delete  
      - run: aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DID --paths "/*"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - react:
          requires:
            - build
        
